
services:
  # User Service Database
  user-db:
    image: postgres:15
    container_name: user-service-db
    environment:
      POSTGRES_DB: user_service_db
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: ecommerce_pass
    ports:
      - "5432:5432"
    volumes:
      - user_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ecommerce_user -d user_service_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Product Service Database
  product-db:
    image: postgres:15
    container_name: product-service-db
    environment:
      POSTGRES_DB: product_service_db
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: ecommerce_pass
    ports:
      - "5433:5432"
    volumes:
      - product_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ecommerce_user -d product_service_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Order Service Database
  order-db:
    image: postgres:15
    container_name: order-service-db
    environment:
      POSTGRES_DB: order_service_db
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: ecommerce_pass
    ports:
      - "5434:5432"
    volumes:
      - order_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ecommerce_user -d order_service_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  cart-db:
    image: postgres:15
    container_name: cart-service-db
    environment:
      POSTGRES_DB: cart_service_db
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: ecommerce_pass
    ports:
      - "5435:5432"
    volumes:
      - cart_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ecommerce_user -d cart_service_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Inventory Service Database
  inventory-db:
    image: postgres:15
    container_name: inventory-service-db
    environment:
      POSTGRES_DB: inventory_service_db
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: ecommerce_pass
    ports:
      - "5436:5432"
    volumes:
      - inventory_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ecommerce_user -d inventory_service_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ecommerce.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8888:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - user-db
      - product-db
      - order-db
      - cart-db
      - inventory-db

volumes:
  user_data:
  product_data:
  order_data:
  cart_data:
  inventory_data:
  pgadmin_data: