spring:
  application:
  name: discovery-server

# Run the discovery server on the standard port 8761
server:
  port: 8761

# Eureka server configuration
eureka:
  client:
    # A Eureka server does not need to register with itself.
    register-with-eureka: false
    # A Eureka server does not need to fetch a copy of the registry from itself.
    fetch-registry: false
  server:
    enable-self-preservation: false


# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

# Application Info
info:
  app:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'
    encoding: '@project.build.sourceEncoding@'
    java:
      version: '@java.version@'

# Logging Configuration
logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
    org.springframework.cloud.netflix.eureka: INFO
    org.springframework.boot.actuate: INFO
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'